base_paths:
  project_root: "."
  data_root: "data"
  geom_data_root: "/nfs/ap/mnt/sxtn2/chem/GEOM_data"
  geom_dataset_root: "/nfs/ap/mnt/sxtn2/chem/GEOM_data/torsional_diff_gdrive/extracted"
  ckpts_root: "/nfs/h100/raid/chem/checkpoints/yerevann"
  hf_yerevann_root: "/nfs/h100/raid/chem/checkpoints/hf/yerevann"
  qwen_yerevann_root: "/nfs/h100/raid/chem/checkpoints/yerevann"
  grpo_root: "/nfs/h100/raid/chem/checkpoints/conf_grpo"
  grpo_outputs_root: "outputs/grpo_outputs"
  gen_results_root: "outputs/gen_results"
  eval_results_root: "outputs/eval_results"
  pretrain_results_root: "outputs/pretrain_results"
  pretrain_logs_root: "outputs/pretrain_logs"
  wandb_root: "wandb_runs"
  qwen3_0.6b_base_model: "/nfs/h100/raid/chem/checkpoints/yerevann/qwen3_06b/Qwen3-0.6B-Base"
  tokenizers_root: "src/molgen3D/training/tokenizers"

data:
  clean_smi: "clean_smi.pickle"
  distinct_smi: "distinct_smi.pickle"
  xl_smi: "xl_smi.pickle"
  qm9_smi: "qm9_smi.pickle"

  rdkit_folder: "rdkit_folder"
  test_mols: "geom_processed/test_smiles_corrected.csv"
  test_mols_xl: "geom_processed/test_smiles_corrected_xl.csv"
  drugs_summary: "rdkit_folder/summary_drugs.json"

  # conformers_train: "geom_processed/geom_cartesian_v2/processed_strings/train"
  # conformers_valid: "geom_processed/geom_cartesian_v2/processed_strings/valid"
  # conformers_test: "geom_processed/geom_cartesian_v2/processed_strings/test"

  GEOM:
    drugs: "DRUGS"
    qm9: "QM9"
    xl: "XL"

  conformers_train: "geom_processed/geom_cartesian_v3/processed_strings/train"
  conformers_valid: "geom_processed/geom_cartesian_v3/processed_strings/valid"
  conformers_test: "geom_processed/geom_cartesian_v3/processed_strings/test"
tokenizers:
  llama3_chem_v1: "src/molgen3D/training/tokenizers/Llama-3.2-chem-1B-v1"
  qwen3_0.6b_custom: "src/molgen3D/training/tokenizers/Qwen3_tokenizer_custom"
  qwen3_0.6b_origin: "src/molgen3D/training/tokenizers/Qwen3_tokenizer_original"
  

models:
  # ---------- BASE MODELS ----------
  m600_qwen:
    root: "qwen3_06b/251208-1746-61f0-qwen3_06b_pre_4e_108effb"
    steps:
      "1e": "step-20000-hf"
      "2e": "step-40000-hf"
      "3e": "step-60000-hf"
      # "4e": "step-80000-hf"
    
  m380_conf:
    root: "Llama-3.2-380M_conformers"
    steps:
      "1e": "b4707c6bf8b54cba8febe9fc/step-8500"
      "2e": "4291f8157d2f41a3bb9605e8/step-16000"
      "3e": "534162de781f4855bbccb0d6/step-23500"
      "4e": "e184d4d867804fbd8a8c45bf/step-30000"

  m380_conf_v2:
    root: "Llama-3.2-380M_conformers/fea47a381e4046e4956dc44a"
    steps:
      "1e": "step-8700"
      "2e": "step-17400"
      "3e": "step-26100"
      "4e": "step-34800"
      
  b1_conf:
    root: "Llama-3.2-1B_conformers"
    steps:
      "1e": "66bfa548d98247cdb01c4c1c/step-11000"
      "2e": "ee7e78995cc04aea8089aee1/step-21000"
      "3e": "de472e134063446086e66925/step-31000"
      "4e": "37cf49f293254a6986b12948/step-40000"

  nb1_conf:
    root: "Llama-3.2-1B_conformers/d151bae44e0d4c868475efa9"
    steps:
      "1e": "step-10000"
      "2e": "step-20000"
      "3e": "step-30000"
      "4e": "step-40000"

  nm380_conf:
    root: "Llama-3.2-380M_conformers/3f3a5585a48c4e13bea8ddb9"
    steps:
      "1e": "step-10000"
      "2e": "step-20000"
      "3e": "step-30000"
      "4e": "step-40000"

  nm170_conf:
    root: "Llama-3.2-170M_conformers/b83c55dc0ab94c22b6eabcb7"
    steps:
      "1e": "step-10000"
      "2e": "step-20000"
      "3e": "step-30000"
      "4e": "step-40000"

  nm100_conf:
    root: "Llama-3.2-100M_conformers/fddd657b71204823aae093c4"
    steps:
      "1e": "step-10000"
      "2e": "step-20000"
      "3e": "step-30000"
      "4e": "step-40000"

  qw600_conf:
    root: "Qwen3-0.6B_hf/05274930efdd48f0a5289a2a"
    steps:
      "1e": "step-14000"
      "2e": "step-28000"
      "3e": "step-42000"
      "4e": "step-56000"

  qw600_pre:
    root: "Qwen3-0.6B/643558083ac449d9b3328bc9"
    steps:
      "1e": "step-13000"
      "2e": "step-26000"
      "3e": "step-39000"
      "4e": "step-52000"

  qw600_src:
    root: "Qwen3-0.6B/823a61f69f184d1d888785e4"
    steps:
      "1e": "step-13000"

  # ---------- GRPO / FINETUNED MODELS (same structure) ----------

  m380_1e_1xgrpo_100e_100s:
    root: "2025-07-30-15:23_380m_1e_lr5e-5_32bs*16comp*6gpu*4ga_100e_1000/code_snapshot/grpo_outputs"
    steps:
      final: "model"
    run_id: "grpo-20250730-1523-m380-1e-100e100s"

  m380_1e_1xgrpo_1e_lr5e-5_algnFalse:
    root: "2025-07-30-23:21_380m_1e_lr5e-5_32bs*16comp*6gpu*4ga_1e_full_algnFalse/code_snapshot/grpo_outputs"
    steps:
      final: "model"
    run_id: "grpo-20250730-2321-m380-1e-af"

  m380_1e_1xgrpo_1e_lr5e-5_algnTrue:
    root: "2025-07-29-10:23_380m_1e_lr5e-5_32bs*16comp*6gpu*4ga_1e_full/code_snapshot/grpo_outputs"
    steps:
      final: "model"
    run_id: "grpo-20250729-1023-m380-1e-at"

  nm380_conf_grpo_alignFalse_v1:
    root: "2025-09-27-11:11_n380m_1e_lr5e-5_256bs*16comp*6gpu*1ga_1e_full"
    steps:
      "500": "checkpoint-500"
      "1000": "checkpoint-1000"
      "1500": "checkpoint-1500"
      "2000": "checkpoint-2000"
      "2231": "checkpoint-2231"
    run_id: "grpo-20250927-1111-nm380-af-v1"

  m380_conf_grpo_alignFalse_v1:
    root: "2025-09-28-19:05_380m_1e_lr5e-5_256bs*16comp*6gpu*1ga_1e_full"
    steps:
      "500": "checkpoint-500"
      "1000": "checkpoint-1000"
      "1500": "checkpoint-1500"
      "2000": "checkpoint-2000"
      "2231": "checkpoint-2231"
    run_id: "grpo-20250928-1905-m380-af-v1"

  m380_conf_grpo_alignTrue_v1:
    root: "2025-09-29-18:06_380m_1e_lr5e-5_256bs*16comp*6gpu*1ga_1e_full_alignTrue"
    steps:
      "500": "checkpoint-500"
      "1000": "checkpoint-1000"
      "1500": "checkpoint-1500"
      "2000": "checkpoint-2000"
      "2231": "checkpoint-2231"
    run_id: "grpo-20250929-1806-m380-at-v1"

  m380_conf_grpo_alignFalse_beta005_v1:
    root: "2025-09-30-16:14_380m_1e_lr5e-5_32bs*16comp*6gpu*8ga_1e_full_beta0.05_alignFalse"
    steps:
      "500": "checkpoint-500"
      "1000": "checkpoint-1000"
      "1500": "checkpoint-1500"
      "2000": "checkpoint-2000"
      "2231": "checkpoint-2231"
    run_id: "grpo-20250930-1614-m380-af-b005-v1"

  m380_4e_conf_grpo_alignFalse_beta005_v1:
    root: "2025-10-02-16:21_380m_4e_lr5e-5_32bs*16comp*6gpu*8ga_1e_full_beta0.05_alignFalse"
    steps:
      final: "model"
    run_id: "grpo-20251002-1621-m380-4e-af-b005-v1"

  m380_4e_conf_grpo_alignFalse_beta005_const05_v1:
    root: "2025-10-06-10:38_380m_4e_lr5e-5_32bs*16comp*6gpu*8ga_1e_full_beta0.05_alignFalse_const0.5"
    steps:
      final: "model"
    run_id: "grpo-20251006-1038-m380-4e-af-b005c05-v1"
