name: 3dmolgen
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - accelerate==1.8.1
    - aiohttp==3.12.13
    - datasets==3.6.0
    - deepspeed==0.17.2
    - flash_attn==2.8.0.post2
    - huggingface-hub==0.33.0
    - numpy==2.2.6
    - pandas==2.3.0
    - Pillow==11.3.0
    - pytorch==2.7.1
    - rdkit==2025.3.3
    - scikit-learn==1.7.0
    - scipy==1.15.3
    - tokenizers==0.21.1
    - torch==2.7.1
    - torchaudio==2.7.1
    - torchvision==0.22.1
    - transformers==4.53.1
    - trl==0.19.1
    - wandb==0.21.0
