name: 3dmolgen
channels:
  - conda-forge
  - nvidia
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=4_kmp_llvm
  - blas=2.116=mkl
  - blas-devel=3.9.0=16_linux64_mkl
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cpython=3.10.18=py310hd8ed1ab_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.9.19=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.9=3
  - filelock=3.19.1=pyhd8ed1ab_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py310h63ebcad_1
  - icu=75.1=he02047a_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - libblas=3.9.0=16_linux64_mkl
  - libcblas=3.9.0=16_linux64_mkl
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.14.1.1=4
  - libcurand=10.3.10.19=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.2.0=h767d61c_6
  - libgcc-ng=15.2.0=h69a702a_6
  - libgfortran=15.2.0=h69a702a_6
  - libgfortran-ng=15.2.0=h69a702a_6
  - libgfortran5=15.2.0=hcd61629_6
  - libgomp=15.2.0=h767d61c_6
  - libhwloc=2.12.1=default_h7f8ec31_1002
  - libiconv=1.18=h3b78370_2
  - liblapack=3.9.0=16_linux64_mkl
  - liblapacke=3.9.0=16_linux64_mkl
  - liblzma=5.8.1=hb9d3cd8_2
  - libnpp=12.0.2.50=0
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libsqlite=3.50.4=h0c1763c_0
  - libstdcxx=15.2.0=h8f9b012_6
  - libstdcxx-ng=15.2.0=h4852527_6
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.15.0=h26afc86_1
  - libxml2-16=2.15.0=ha9997c6_1
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=15.0.7=h0cdce71_0
  - markupsafe=3.0.3=py310h3406613_0
  - mkl=2022.1.0=h84fe81f_915
  - mkl-devel=2022.1.0=ha770c72_916
  - mkl-include=2022.1.0=h84fe81f_915
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - networkx=3.4.2=pyh267e887_2
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openssl=3.5.4=h26f9b46_0
  - pip=25.2=pyh8b19718_0
  - python=3.10.18=hd6af730_0_cpython
  - python_abi=3.10=8_cp310
  - pytorch=2.5.1=py3.10_cuda12.1_cudnn9.1.0_0
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.3=py310h3406613_0
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tbb=2021.13.0=hb60516a_3
  - tk=8.6.13=noxft_hd72426e_102
  - torchtriton=3.1.0=py310
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - yaml=0.2.5=h280c20c_3
  - pip:
    - accelerate==1.10.1
    - aim==3.29.1
    - aim-ui==3.29.1
    - aimrecords==0.0.7
    - aimrocks==0.5.2
    - aiofiles==25.1.0
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.12.13
    - aiosignal==1.3.2
    - alembic==1.17.0
    - annotated-types==0.7.0
    - anyio==4.11.0
    - asttokens==3.0.0
    - async-timeout==5.0.1
    - attrs==25.4.0
    - base58==2.0.1
    - boto3==1.40.52
    - botocore==1.40.52
    - cachetools==6.2.1
    - certifi==2025.10.5
    - cffi==2.0.0
    - charset-normalizer==3.4.2
    - click==8.3.0
    - cloudpickle==3.1.1
    - comm==0.2.3
    - contourpy==1.3.2
    - cryptography==46.0.2
    - cycler==0.12.1
    - datamol==0.12.5
    - datasets==3.6.0
    - debugpy==1.8.17
    - decorator==5.2.1
    - dill==0.3.8
    - einops==0.8.0
    - exceptiongroup==1.3.0
    - executing==2.2.1
    - fastapi==0.119.0
    - filelock==3.18.0
    - flash_attn==2.8.3
    - fonttools==4.58.4
    - frozenlist==1.7.0
    - fsspec==2025.3.0
    - git-filter-repo==2.47.0
    - gitdb==4.0.12
    - GitPython==3.1.44
    - Glances==4.3.3
    - greenlet==3.2.4
    - h11==0.16.0
    - hf-xet==1.1.3
    - hjson==3.1.0
    - huggingface-hub==0.35.3
    - idna==3.10
    - importlib_resources==6.5.2
    - iniconfig==2.3.0
    - ipykernel==6.30.1
    - ipython==8.37.0
    - jedi==0.19.2
    - jmespath==1.0.1
    - joblib==1.5.1
    - jupyter_client==8.6.3
    - jupyter_core==5.8.1
    - kiwisolver==1.4.8
    - liger_kernel==0.6.2
    - loguru==0.7.3
    - Mako==1.3.10
    - matplotlib==3.10.6
    - matplotlib-inline==0.1.7
    - "-e git+ssh://git@github.com/YerevaNN/3DMolGen.git@42b74e7f38ef03e6ab7c43b12b03146116f046e3#egg=molgen3D"
    - mpmath==1.3.0
    - msgpack==1.1.1
    - multidict==6.4.4
    - multiprocess==0.70.16
    - nest-asyncio==1.6.0
    - networkx==3.4.2
    - ninja==1.11.1.4
    - numpy==2.2.6
    - nvidia-cufile-cu12==1.11.1.6
    - nvidia-ml-py==12.575.51
    - packaging==25.0
    - pandas==2.3.0
    - parso==0.8.5
    - pexpect==4.9.0
    - pillow==11.3.0
    - platformdirs==4.3.8
    - pluggy==1.6.0
    - posebusters==0.4.4
    - prompt_toolkit==3.0.52
    - propcache==0.3.2
    - protobuf==6.31.1
    - psutil==7.0.0
    - ptyprocess==0.7.0
    - pure_eval==0.2.3
    - py-cpuinfo==9.0.0
    - pyarrow==20.0.0
    - pycparser==2.23
    - pydantic==2.11.7
    - pydantic_core==2.33.2
    - Pygments==2.19.2
    - pyparsing==3.2.5
    - pytest==8.4.2
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - PyYAML==6.0.2
    - pyzmq==27.1.0
    - rdkit==2025.3.3
    - regex==2024.11.6
    - requests==2.32.4
    - RestrictedPython==8.0
    - s3transfer==0.14.0
    - safetensors==0.5.3
    - scikit-learn==1.7.0
    - scipy==1.15.3
    - selfies==2.2.0
    - sentry-sdk==2.30.0
    - setproctitle==1.3.6
    - shtab==1.7.2
    - six==1.17.0
    - smmap==5.0.2
    - sniffio==1.3.1
    - SQLAlchemy==2.0.44
    - stack-data==0.6.3
    - starlette==0.48.0
    - submitit==1.5.3
    - sympy==1.13.1
    - threadpoolctl==3.6.0
    - tokenizer==3.5.1
    - tokenizers==0.22.1
    - tomli==2.3.0
    - torch==2.5.1
    - tornado==6.5.2
    - tqdm==4.67.1
    - traitlets==5.14.3
    - transformers==4.57.0
    - triton==3.1.0
    - trl==0.23.0
    - typing-inspection==0.4.1
    - typing_extensions==4.14.0
    - tzdata==2025.2
    - urllib3==2.4.0
    - uvicorn==0.37.0
    - wandb==0.21.0
    - watchdog==6.0.0
    - wcwidth==0.2.14
    - websockets==15.0.1
    - xxhash==3.5.0
    - yarl==1.20.1
