[job]
description = "basic qwen3 training"

[model]
name = "qwen3"
flavor = "0.6B"
hf_assets_path = "src/molgen3D/training/tokenizers/Qwen3_tokenizer_original"

[training]
dataset = "c4_test"
dataset_path = "tests/assets/c4_test"
local_batch_size = 1
seq_len = 2048
steps = 10
dtype = "float32"

[optimizer]
name = "AdamW"
lr = 1e-4

[lr_scheduler]
warmup_steps = 2
decay_type = "cosine"
