model_paths:
  m380_1e: "/nfs/h100/raid/chem/checkpoints/hf/yerevann/Llama-3.2-380M_conformers/b4707c6bf8b54cba8febe9fc/step-8500/"
  m380_2e: "/nfs/h100/raid/chem/checkpoints/hf/yerevann/Llama-3.2-380M_conformers/4291f8157d2f41a3bb9605e8/step-16000/"
  m380_3e: "/nfs/h100/raid/chem/checkpoints/hf/yerevann/Llama-3.2-380M_conformers/534162de781f4855bbccb0d6/step-23500/"
  m380_4e: "/nfs/h100/raid/chem/checkpoints/hf/yerevann/Llama-3.2-380M_conformers/e184d4d867804fbd8a8c45bf/step-30000/"

  m380_1e_1xgrpo_100e_100s: "/auto/home/menuab/code/3DMolGen/grpo_outputs/2025-07-30-15:23_380m_1e_lr5e-5_32bs*16comp*6gpu*4ga_100e_1000/code_snapshot/grpo_outputs/model"
  m380_1e_1xgrpo_1e_lr5e-5_algnFalse: "/auto/home/menuab/code/3DMolGen/grpo_outputs/2025-07-30-23:21_380m_1e_lr5e-5_32bs*16comp*6gpu*4ga_1e_full_algnFalse/code_snapshot/grpo_outputs/model"
  m380_1e_1xgrpo_1e_lr5e-5_algnTrue: "/auto/home/menuab/code/3DMolGen/grpo_outputs/2025-07-29-10:23_380m_1e_lr5e-5_32bs*16comp*6gpu*4ga_1e_full/code_snapshot/grpo_outputs/model"
  
  b1_1e: "/nfs/h100/raid/chem/checkpoints/hf/yerevann/Llama-3.2-1B_conformers/66bfa548d98247cdb01c4c1c/step-11000/"
  b1_2e: "/nfs/h100/raid/chem/checkpoints/hf/yerevann/Llama-3.2-1B_conformers/ee7e78995cc04aea8089aee1/step-21000/"
  b1_3e: "/nfs/h100/raid/chem/checkpoints/hf/yerevann/Llama-3.2-1B_conformers/de472e134063446086e66925/step-31000/"
  b1_4e: "/nfs/h100/raid/chem/checkpoints/hf/yerevann/Llama-3.2-1B_conformers/37cf49f293254a6986b12948/step-40000/"

tokenizer_path: "/auto/home/menuab/code/YNNtitan/torchtitan/tokenizers/Llama-3.2-chem-1B-v1"
test_data_path: "/auto/home/menuab/code/3DMolGen/data/geom_drugs_test_set/drugs_test_inference.pickle"
results_path: "/auto/home/menuab/code/3DMolGen/gen_results"