model_paths:
  m380_1e: "/nfs/h100/raid/chem/checkpoints/hf/yerevann/Llama-3.2-380M_conformers/b4707c6bf8b54cba8febe9fc/step-8500/"
  m380_2e: "/nfs/h100/raid/chem/checkpoints/hf/yerevann/Llama-3.2-380M_conformers/4291f8157d2f41a3bb9605e8/step-16000/"
  m380_3e: "/nfs/h100/raid/chem/checkpoints/hf/yerevann/Llama-3.2-380M_conformers/534162de781f4855bbccb0d6/step-23500/"
  m380_4e: "/nfs/h100/raid/chem/checkpoints/hf/yerevann/Llama-3.2-380M_conformers/e184d4d867804fbd8a8c45bf/step-30000/"

  m380_1e_1xgrpo_100e_100s: "/auto/home/menuab/code/3DMolGen/grpo_outputs/2025-07-30-15:23_380m_1e_lr5e-5_32bs*16comp*6gpu*4ga_100e_1000/code_snapshot/grpo_outputs/model"
  m380_1e_1xgrpo_1e_lr5e-5_algnFalse: "/auto/home/menuab/code/3DMolGen/grpo_outputs/2025-07-30-23:21_380m_1e_lr5e-5_32bs*16comp*6gpu*4ga_1e_full_algnFalse/code_snapshot/grpo_outputs/model"
  m380_1e_1xgrpo_1e_lr5e-5_algnTrue: "/auto/home/menuab/code/3DMolGen/grpo_outputs/2025-07-29-10:23_380m_1e_lr5e-5_32bs*16comp*6gpu*4ga_1e_full/code_snapshot/grpo_outputs/model"
  
  b1_1e: "/nfs/h100/raid/chem/checkpoints/hf/yerevann/Llama-3.2-1B_conformers/66bfa548d98247cdb01c4c1c/step-11000/"
  b1_2e: "/nfs/h100/raid/chem/checkpoints/hf/yerevann/Llama-3.2-1B_conformers/ee7e78995cc04aea8089aee1/step-21000/"
  b1_3e: "/nfs/h100/raid/chem/checkpoints/hf/yerevann/Llama-3.2-1B_conformers/de472e134063446086e66925/step-31000/"
  b1_4e: "/nfs/h100/raid/chem/checkpoints/hf/yerevann/Llama-3.2-1B_conformers/37cf49f293254a6986b12948/step-40000/"

  nb1_1e: "/nfs/h100/raid/chem/checkpoints/hf/yerevann/Llama-3.2-1B_conformers/d151bae44e0d4c868475efa9/step-10000"
  nb1_2e: "/nfs/h100/raid/chem/checkpoints/hf/yerevann/Llama-3.2-1B_conformers/d151bae44e0d4c868475efa9/step-20000"
  nb1_3e: "/nfs/h100/raid/chem/checkpoints/hf/yerevann/Llama-3.2-1B_conformers/d151bae44e0d4c868475efa9/step-30000"
  nb1_4e: "/nfs/h100/raid/chem/checkpoints/hf/yerevann/Llama-3.2-1B_conformers/d151bae44e0d4c868475efa9/step-40000"

  nm380_1e: "/nfs/h100/raid/chem/checkpoints/hf/yerevann/Llama-3.2-380M_conformers/3f3a5585a48c4e13bea8ddb9/step-10000"
  nm380_2e: "/nfs/h100/raid/chem/checkpoints/hf/yerevann/Llama-3.2-380M_conformers/3f3a5585a48c4e13bea8ddb9/step-20000"
  nm380_3e: "/nfs/h100/raid/chem/checkpoints/hf/yerevann/Llama-3.2-380M_conformers/3f3a5585a48c4e13bea8ddb9/step-30000"
  nm380_4e: "/nfs/h100/raid/chem/checkpoints/hf/yerevann/Llama-3.2-380M_conformers/3f3a5585a48c4e13bea8ddb9/step-40000"

  nm170_1e: "/nfs/h100/raid/chem/checkpoints/hf/yerevann/Llama-3.2-170M_conformers/b83c55dc0ab94c22b6eabcb7/step-10000"
  nm170_2e: "/nfs/h100/raid/chem/checkpoints/hf/yerevann/Llama-3.2-170M_conformers/b83c55dc0ab94c22b6eabcb7/step-20000"
  nm170_3e: "/nfs/h100/raid/chem/checkpoints/hf/yerevann/Llama-3.2-170M_conformers/b83c55dc0ab94c22b6eabcb7/step-30000"
  nm170_4e: "/nfs/h100/raid/chem/checkpoints/hf/yerevann/Llama-3.2-170M_conformers/b83c55dc0ab94c22b6eabcb7/step-40000"

  nm100_1e: "/nfs/h100/raid/chem/checkpoints/hf/yerevann/Llama-3.2-100M_conformers/fddd657b71204823aae093c4/step-10000"
  nm100_2e: "/nfs/h100/raid/chem/checkpoints/hf/yerevann/Llama-3.2-100M_conformers/fddd657b71204823aae093c4/step-20000"
  nm100_3e: "/nfs/h100/raid/chem/checkpoints/hf/yerevann/Llama-3.2-100M_conformers/fddd657b71204823aae093c4/step-30000"
  nm100_4e: "/nfs/h100/raid/chem/checkpoints/hf/yerevann/Llama-3.2-100M_conformers/fddd657b71204823aae093c4/step-40000"

  nm380_500grpo_alignFalse: "/nfs/h100/raid/chem/checkpoints/conf_grpo/2025-09-27-11:11_n380m_1e_lr5e-5_256bs*16comp*6gpu*1ga_1e_full/checkpoint-500"
  nm380_1000grpo_alignFalse: "/nfs/h100/raid/chem/checkpoints/conf_grpo/2025-09-27-11:11_n380m_1e_lr5e-5_256bs*16comp*6gpu*1ga_1e_full/checkpoint-1000"
  nm380_1500grpo_alignFalse: "/nfs/h100/raid/chem/checkpoints/conf_grpo/2025-09-27-11:11_n380m_1e_lr5e-5_256bs*16comp*6gpu*1ga_1e_full/checkpoint-1500"
  nm380_2000grpo_alignFalse: "/nfs/h100/raid/chem/checkpoints/conf_grpo/2025-09-27-11:11_n380m_1e_lr5e-5_256bs*16comp*6gpu*1ga_1e_full/checkpoint-2000"
  nm380_2230grpo_alignFalse: "/nfs/h100/raid/chem/checkpoints/conf_grpo/2025-09-27-11:11_n380m_1e_lr5e-5_256bs*16comp*6gpu*1ga_1e_full/checkpoint-2231"

  m380_500grpo_alignFalse: "/nfs/h100/raid/chem/checkpoints/conf_grpo/2025-09-28-19:05_380m_1e_lr5e-5_256bs*16comp*6gpu*1ga_1e_full/checkpoint-500"
  m380_1000grpo_alignFalse: "/nfs/h100/raid/chem/checkpoints/conf_grpo/2025-09-28-19:05_380m_1e_lr5e-5_256bs*16comp*6gpu*1ga_1e_full/checkpoint-1000"
  m380_1500grpo_alignFalse: "/nfs/h100/raid/chem/checkpoints/conf_grpo/2025-09-28-19:05_380m_1e_lr5e-5_256bs*16comp*6gpu*1ga_1e_full/checkpoint-1500"
  m380_2000grpo_alignFalse: "/nfs/h100/raid/chem/checkpoints/conf_grpo/2025-09-28-19:05_380m_1e_lr5e-5_256bs*16comp*6gpu*1ga_1e_full/checkpoint-2000"
  m380_2230grpo_alignFalse: "/nfs/h100/raid/chem/checkpoints/conf_grpo/2025-09-28-19:05_380m_1e_lr5e-5_256bs*16comp*6gpu*1ga_1e_full/checkpoint-2231"

  m380_500grpo_alignTrue: "/nfs/h100/raid/chem/checkpoints/conf_grpo/2025-09-29-18:06_380m_1e_lr5e-5_256bs*16comp*6gpu*1ga_1e_full_alignTrue/checkpoint-500"
  m380_1000grpo_alignTrue: "/nfs/h100/raid/chem/checkpoints/conf_grpo/2025-09-29-18:06_380m_1e_lr5e-5_256bs*16comp*6gpu*1ga_1e_full_alignTrue/checkpoint-1000"
  m380_1500grpo_alignTrue: "/nfs/h100/raid/chem/checkpoints/conf_grpo/2025-09-29-18:06_380m_1e_lr5e-5_256bs*16comp*6gpu*1ga_1e_full_alignTrue/checkpoint-1500"
  m380_2000grpo_alignTrue: "/nfs/h100/raid/chem/checkpoints/conf_grpo/2025-09-29-18:06_380m_1e_lr5e-5_256bs*16comp*6gpu*1ga_1e_full_alignTrue/checkpoint-2000"
  m380_2230grpo_alignTrue: "/nfs/h100/raid/chem/checkpoints/conf_grpo/2025-09-29-18:06_380m_1e_lr5e-5_256bs*16comp*6gpu*1ga_1e_full_alignTrue/checkpoint-2231"

  m380_500grpo_aF_b05: "/nfs/h100/raid/chem/checkpoints/conf_grpo/2025-09-30-16:14_380m_1e_lr5e-5_32bs*16comp*6gpu*8ga_1e_full_beta0.05_alignFalse/checkpoint-500"
  m380_1000grpo_aF_b05: "/nfs/h100/raid/chem/checkpoints/conf_grpo/2025-09-30-16:14_380m_1e_lr5e-5_32bs*16comp*6gpu*8ga_1e_full_beta0.05_alignFalse/checkpoint-1000"
  m380_1500grpo_aF_b05: "/nfs/h100/raid/chem/checkpoints/conf_grpo/2025-09-30-16:14_380m_1e_lr5e-5_32bs*16comp*6gpu*8ga_1e_full_beta0.05_alignFalse/checkpoint-1500"
  m380_2000grpo_aF_b05: "/nfs/h100/raid/chem/checkpoints/conf_grpo/2025-09-30-16:14_380m_1e_lr5e-5_32bs*16comp*6gpu*8ga_1e_full_beta0.05_alignFalse/checkpoint-2000"
  m380_2230grpo_aF_b05: "/nfs/h100/raid/chem/checkpoints/conf_grpo/2025-09-30-16:14_380m_1e_lr5e-5_32bs*16comp*6gpu*8ga_1e_full_beta0.05_alignFalse/checkpoint-2231"


tokenizer_path: "/auto/home/menuab/code/YNNtitan/torchtitan/tokenizers/Llama-3.2-chem-1B-v1"
# test_data_path: "/auto/home/menuab/code/3DMolGen/data/geom_drugs_test_set/drugs_test_inference.pickle"
test_data_path: 
  corrected_smi: "/auto/home/menuab/code/3DMolGen/data/inference_set_corrected_smiles/drugs_test_dict.pickle"
  clean_smi: "/auto/home/menuab/code/3DMolGen/data/inference_set_clean_smiles/drugs_test_dict.pickle"
  distinct_smi: "/auto/home/menuab/code/3DMolGen/data/inference_set_distinct_smiles/drugs_test_dict.pickle"
results_path: "/auto/home/menuab/code/3DMolGen/gen_results"